services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"
        networks:
            - internal
        volumes:
            - ./src/:/var/www/html/
            - ./docker/logs/nginx/:/var/log/nginx/
    php:
        image: php:fpm-alpine
        networks:
            - internal
        volumes:
            - ./src/:/var/www/html/
            - ./docker/logs//php.log:/var/log/fpm-php.www.log
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_PASSWORD: password
        networks:
            - internal
    phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 9000:80
        links:
            - mysql
        networks:
            - internal
networks:
  internal:
    driver: bridge
